[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev --workspace=server --include-workspace-root"

[deploy]
startCommand = "npm run start -w server"
restartPolicyType = "on_failure"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
